### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by carolallanos** [PopupMaker/Library#12]
It closes the popup after 5 secs without submiting any forms

**Comment by marklchaves** [comment]
Hey @carolallanos,

The best place to get Popup Maker help is on our forum (not here on GitHub). Here's the link.

https://wordpress.org/support/plugin/popup-maker/

Can you please post your question there?

Be sure to follow these guidelines to avoid extra back and forth.

https://wordpress.org/support/topic/construct-your-support-thread-like-this-to-get-the-fastest-support/

Cheers! 😌
